2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_setup.py:_flush():67] Configure stats pid to 105369
2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_setup.py:_flush():67] Loading settings from /home/mezallamosas.j/.config/wandb/settings
2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_setup.py:_flush():67] Loading settings from /home/mezallamosas.j/nlp2025/wandb/settings
2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/mezallamosas.j/nlp2025/wandb/run-20250311_191809-vv1jlrcr/logs/debug.log
2025-03-11 19:18:09,925 INFO    Thread-11 :105369 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/mezallamosas.j/nlp2025/wandb/run-20250311_191809-vv1jlrcr/logs/debug-internal.log
2025-03-11 19:18:09,926 INFO    Thread-11 :105369 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2b5e3e73f0a0>
2025-03-11 19:18:09,927 INFO    Thread-11 :105369 [wandb_init.py:init():761] calling init triggers
2025-03-11 19:18:09,927 INFO    Thread-11 :105369 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 128, 'embeddings_size': 50, 'epochs': 5, 'hidden_units': 128, 'lr': 0.001, 'ngram': 3, 'test_pct': 0.1}
config: {'_wandb': {}}
2025-03-11 19:18:09,927 INFO    Thread-11 :105369 [wandb_init.py:init():784] starting backend
2025-03-11 19:18:09,927 INFO    Thread-11 :105369 [wandb_init.py:init():788] sending inform_init request
2025-03-11 19:18:09,930 INFO    Thread-11 :105369 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-11 19:18:09,930 INFO    Thread-11 :105369 [wandb_init.py:init():798] backend started and connected
2025-03-11 19:18:09,939 INFO    Thread-11 :105369 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 128, 'embeddings_size': 50, 'epochs': 5, 'hidden_units': 128, 'lr': 0.001, 'ngram': 3, 'test_pct': 0.1}
2025-03-11 19:18:09,956 INFO    Thread-11 :105369 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-11 19:18:09,957 INFO    Thread-11 :105369 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-11 19:18:09,957 INFO    Thread-11 :105369 [wandb_init.py:init():891] updated telemetry
2025-03-11 19:18:10,027 INFO    Thread-11 :105369 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-11 19:18:10,234 INFO    Thread-11 :105369 [wandb_init.py:init():990] starting run threads in backend
2025-03-11 19:18:10,593 INFO    Thread-11 :105369 [wandb_run.py:_console_start():2375] atexit reg
2025-03-11 19:18:10,593 INFO    Thread-11 :105369 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-11 19:18:10,594 INFO    Thread-11 :105369 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-11 19:18:10,594 INFO    Thread-11 :105369 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-11 19:18:10,594 INFO    Thread-11 :105369 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-11 19:19:41,741 INFO    MainThread:105369 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-11 19:19:41,742 INFO    MainThread:105369 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-11 19:19:45,685 INFO    MainThread:105369 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-11 19:19:45,687 INFO    MainThread:105369 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-11 19:19:45,687 INFO    MainThread:105369 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-11 19:19:50,597 INFO    MsgRouterThr:105369 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-11 19:19:51,097 ERROR   Thread-2  :105369 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mezallamosas.j/.conda/envs/nlp/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
